# Generated by Django 3.2.25 on 2024-10-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20241002_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_invited',
            field=models.BooleanField(default=False, verbose_name='是否邀约'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_joined',
            field=models.BooleanField(default=False, verbose_name='是否入群'),
        ),
    ]
