# Generated by Django 3.2.25 on 2024-10-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20241002_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='data_source',
            field=models.CharField(choices=[('ai', 'AI数据'), ('video_number', '视频号'), ('other', '其他')], default='ai', max_length=100, verbose_name='数据来源'),
        ),
    ]
