# Generated by Django 3.2.25 on 2024-10-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='intention',
            field=models.CharField(choices=[('low', '低意向'), ('moderate', '中等意向'), ('high', '高意向'), ('unknow', '未知')], default='low', max_length=20, verbose_name='意向程度'),
        ),
    ]
