# Generated by Django 3.2.25 on 2024-10-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_intention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='intention',
            field=models.CharField(choices=[('low', '低意向'), ('medium', '中等意向'), ('high', '高意向'), ('unknow', '未知')], default='low', max_length=20, verbose_name='意向程度'),
        ),
    ]
