# Generated by Django 3.2.25 on 2024-10-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_intention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='data_source',
            field=models.CharField(choices=[('AI数据', 'AI数据'), ('视频号', '视频号'), ('其他', '其他')], default='ai', max_length=100, verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='education',
            field=models.CharField(choices=[('大专以下', '大专以下'), ('大专', '大专'), ('本科', '本科'), ('研究生及以上', '研究生及以上'), ('未知', '未知')], default='大专', max_length=20, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='intention',
            field=models.CharField(choices=[('低', '低'), ('中', '中'), ('高', '高'), ('未知', '未知')], default='低', max_length=20, verbose_name='意向程度'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='major_category',
            field=models.CharField(choices=[('IT', 'IT'), ('非IT', '非IT'), ('未知', '未知')], default='IT', max_length=10, verbose_name='专业类别'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('在职', '在职'), ('待业', '待业'), ('未知', '未知')], default='待业', max_length=15, verbose_name='状态'),
        ),
    ]
